### PR TITLE
Note that RPU has freely-licensed EOS M50 samples

### PR DESCRIPTION
**Pull request by LebedevRI**
It's kinda the purpose of that archive :)

### CODE REVIEW

**Review by lclevy — APPROVED** [review]
thanks

**Comment by LebedevRI** [comment]
thanks :)

**Comment by lclevy** [comment]
Hi, 
could you please ask a m50 user to provide raw and c-raw in continuous mode? It seems it is 12bits. See p203 in manual.
https://www.canon.co.uk/support/consumer_products/products/cameras/digital_slr/eos-m50.html?type=manuals&language=
Spasiba

**Comment by brontide** [comment]
So with the camera set on M with continuous shooting two sets, one of C-RAW and one of RAW?  Any particular naming scheme? @lclevy 

```
m50-continuous-manual-RAW-#.cr3
m50-continuous-manual-CRAW-#.cr3
```

**Comment by LebedevRI** [comment]
Existing samples are named: https://raw.pixls.us/data/Canon/Canon%20EOS%20M50/
So something like `Canon-EOS_M50_-{,C}RAW_(3:2)_continuous.CR3` maybe.

**Comment by mvoorhis** [comment]
This is  out-of-subject, but I should receive a new Canon 90D in about one week (12-16 September), and will be able to supply files/data if there is a need for any.  There are samples on dpreview for example, but I don't know if they are restricted use.

**Comment by LebedevRI** [comment]
> 90D

I don't see any samples on RPU so yes please, do submit the full set :)
(Please rename files before upload!)

**Comment by mvoorhis** [comment]
Here are four files -- Canon 90D RAW and cRAW, with corresponding JPEG
from the camera.  You may upload the files from here:;

   https://www.mcvau.net/~mvoorhis/share/20191013-RawPix/

There is no license on these files, you are free to do whatever you want
with the pictures, etc. etc.  Please let me know when you have the
files, as I will remove them from the webserver here.

--MCV.

**Comment by lclevy** [comment]
Hi,
There is a permission issue to download files

**Comment by LebedevRI** [comment]
In the mean time 90D samples were provided by someone: https://raw.pixls.us/data/Canon/Canon%20EOS%2090D/

**Comment by lclevy** [comment]
Is there any c-raw?

**Comment by LebedevRI** [comment]
Half of the set, yes. `https://raw.pixls.us/getfile.php/3412/raw/IMG_116[1-4].CR3`

**Pull request merged**
